name: Import APIs to APIM

on:
  push:
    branches:
      - main
jobs:
  test_openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI

    steps:
      - uses: actions/checkout@v2
      - name: Validate OpenAPI with API Fuzzer
        run: |
          docker pull quay.io/ceye/api-fuzzer
          docker run --rm -v $(pwd):/data quay.io/ceye/api-fuzzer validate /data/apis/**/*.yaml

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Import APIs
        run: |
          for file in ./apis/*.yaml; do
            az apim api import --resource-group ${{ secrets.RESOURCE_GROUP }} --service-name ${{ secrets.APIM_INSTANCE }} --specification-format OpenApi --specification-path $file --path /${file##*/}
          done
